version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DatabaseSettings__ConnectionString=Server=docker
    ports:
      - "8001:80"
      - "8002:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro